INSERT INTO recipes(description, foto, ingredients, portions, `time`, title) VALUES('Pane classico da condividere', 'https://healthy.thewom.it/wp-content/uploads/2023/05/pane.jpg', 'Farina, sale e amore', 2, '2 ore', 'Pane :)');
INSERT INTO recipes(description, foto, ingredients, portions, `time`, title) VALUES('Pesto alla genovese verde verde verde', 'https://blog.giallozafferano.it/allacciateilgrembiule/wp-content/uploads/2018/04/pesto-genovese3.jpg', 'Basilico, formaggio, pinoli, aglio, olio, sale e amore', 3, '1 ora', 'Pesto alla Genovese');
INSERT INTO recipes(description, foto, ingredients, portions, `time`, title) VALUES('Ragù alla bolognese rosso rosso rosso', 'https://www.giallozafferano.it/images/229-22935/Ragu-alla-bolognese_450x300.jpg', 'Carne, pomodori, carotte, sale e amore', 3, '30 min', 'Ragù alla bolognese');
INSERT INTO recipes(description, foto, ingredients, portions, `time`, title) VALUES('Aglio, olio e pepperoncino super mega ultra piccante', 'https://www.giallozafferano.it/images/184-18493/Spaghetti-aglio-olio-e-peperoncino_450x300.jpg', 'Aglio, pepperoncino, pasta, sale, prezzemolo e amore', 1, '20 min', 'Aglio, Olio e Pepperoncino');
INSERT INTO recipes(description, foto, ingredients, portions, `time`, title) VALUES('Pasta alla carbonara gialla gialla gialla', 'https://www.giallozafferano.it/images/244-24489/Spaghetti-alla-Carbonara_450x300_sp.jpg', 'Uova, pasta, peppe, guancialle, sale e amore', 1, '30 min', 'Pasta alla carbonara');
INSERT INTO categories(name) VALUES('Antipasto');
INSERT INTO categories(name) VALUES('Primo Piatto');
INSERT INTO categories(name) VALUES('Secondo Piatto');
INSERT INTO categories(name) VALUES('Contorno');
INSERT INTO categories(name) VALUES('Dessert');
